package com.blog.po;

/**
 * BllAttachment generated by hbm2java
 */
public class BllAttachment extends BaseModel {

	private String attName;
	private String attPath;
	private String articleId;
	private Integer attSize;

	public String getAttName() {
		return attName;
	}

	public void setAttName(String attName) {
		this.attName = attName;
	}

	public String getAttPath() {
		return attPath;
	}

	public void setAttPath(String attPath) {
		this.attPath = attPath;
	}

	public String getArticleId() {
		return articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public Integer getAttSize() {
		return attSize;
	}

	public void setAttSize(Integer attSize) {
		this.attSize = attSize;
	}

}
