package com.blog.po;

/**
 * BllCommont generated by hbm2java
 */
public class BllCommont extends BaseModel {

	private String articleId;
	private String articleTitle;
	private String comContent;

	public String getArticleId() {
		return articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	public String getComContent() {
		return comContent;
	}

	public void setComContent(String comContent) {
		this.comContent = comContent;
	}

}
