package com.blog.po;
// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * BllFavuser generated by hbm2java
 */
public class BllFavuser extends BaseModel {

	private String favUser;
	private String describle;

	public String getFavUser() {
		return favUser;
	}

	public void setFavUser(String favUser) {
		this.favUser = favUser;
	}

	public String getDescrible() {
		return describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

}
