package com.blog.po;

/**
 * BllFavarticle generated by hbm2java
 */
public class BllFavarticle extends BaseModel {

	private String articleTitle;
	private String describle;
	private String articleUrl;

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	public String getDescrible() {
		return describle;
	}

	public void setDescrible(String describle) {
		this.describle = describle;
	}

	public String getArticleUrl() {
		return articleUrl;
	}

	public void setArticleUrl(String articleUrl) {
		this.articleUrl = articleUrl;
	}

}
