package com.blog.po;

/**
 * BllPageinfo generated by hbm2java
 */
public class BllPageinfo extends BaseModel {

	private String url;
	private String title;
	private String postTime;
	private String content;
	private String author;
	private String authorPage;

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPostTime() {
		return postTime;
	}

	public void setPostTime(String postTime) {
		this.postTime = postTime;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getAuthorPage() {
		return authorPage;
	}

	public void setAuthorPage(String authorPage) {
		this.authorPage = authorPage;
	}

}
