package com.blog.po;

/**
 * BllSuggest generated by hbm2java
 */
public class BllSuggest extends BaseModel {

	private String articleId;
	private String articleTitle;

	public String getArticleId() {
		return articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

}
