package com.blog.po;

// Generated 2017-4-2 12:37:59 by Hibernate Tools 5.2.1.Final

/**
 * SysUsers generated by hbm2java
 */
public class SysUser extends BaseModel {

	private String userCode;
	private String userPassword;
	private String userName;
	private String email;
	private String photoPath;
	private String photoFingerPrint;

	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserPassword() {
		return userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhotoPath() {
		return photoPath;
	}

	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	public String getPhotoFingerPrint() {
		return photoFingerPrint;
	}

	public void setPhotoFingerPrint(String photoFingerPrint) {
		this.photoFingerPrint = photoFingerPrint;
	}

}
